// SPDX-License-Identifier: GPL-3.0-or-later
using System.Text;

namespace Bindery.Ra2.Adapter;

public static class SpawnIniRenderer
{
    public static string Render(SpawnConfiguration configuration)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(configuration.GameExecutable);
        ArgumentException.ThrowIfNullOrWhiteSpace(configuration.MapId);
        ArgumentException.ThrowIfNullOrWhiteSpace(configuration.PlayerName);
        ValidateValue(configuration.GameExecutable, nameof(configuration.GameExecutable));
        ValidateValue(configuration.MapId, nameof(configuration.MapId));
        ValidateValue(configuration.PlayerName, nameof(configuration.PlayerName));
        if (configuration.RelayHost is not null) ValidateValue(configuration.RelayHost, nameof(configuration.RelayHost));

        SortedDictionary<string, string> values = new(StringComparer.Ordinal)
        {
            ["GameExecutable"] = configuration.GameExecutable,
            ["Map"] = configuration.MapId,
            ["PlayerName"] = configuration.PlayerName,
            ["SpawnMode"] = configuration.SpawnMode,
        };
        if (configuration.RelayHost is not null) values["RelayHost"] = configuration.RelayHost;
        if (configuration.RelayPort is not null) values["RelayPort"] = configuration.RelayPort.Value.ToString(System.Globalization.CultureInfo.InvariantCulture);

        StringBuilder output = new("; Generated by Bindery RA2 adapter. Do not commit.\r\n[Multiplayer]\r\n");
        foreach ((string key, string value) in values) output.Append(key).Append('=').Append(value).Append("\r\n");
        return output.ToString();
    }

    private static void ValidateValue(string value, string name)
    {
        if (value.Contains('\r') || value.Contains('\n') || value.Contains('\0')) throw new ArgumentException($"{name} contains a forbidden control character", name);
    }
}

