// SPDX-License-Identifier: GPL-3.0-or-later
using System.Globalization;
using System.Text;

namespace Bindery.Ra2.Adapter;

public static class SpawnIniRenderer
{
    public static string Render(SpawnConfiguration configuration)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(configuration.GameExecutable);
        ArgumentException.ThrowIfNullOrWhiteSpace(configuration.MapId);
        ArgumentException.ThrowIfNullOrWhiteSpace(configuration.PlayerName);
        ValidateValue(configuration.GameExecutable, nameof(configuration.GameExecutable));
        ValidateValue(configuration.MapId, nameof(configuration.MapId));
        ValidateValue(configuration.PlayerName, nameof(configuration.PlayerName));
        if (configuration.RelayHost is not null) ValidateValue(configuration.RelayHost, nameof(configuration.RelayHost));

        SortedDictionary<string, string> values = new(StringComparer.Ordinal)
        {
            ["ForceMultiplayer"] = "true",
            ["Name"] = configuration.PlayerName,
            ["Ra2Mode"] = "true",
            ["Scenario"] = configuration.MapId,
            ["WriteStatistics"] = "true",
        };

        StringBuilder output = new("; Generated by Bindery RA2/YR adapter. Do not commit.\r\n[Settings]\r\n");
        foreach ((string key, string value) in values) output.Append(key).Append('=').Append(value).Append("\r\n");
        if (configuration.RelayHost is not null && configuration.RelayPort is not null)
        {
            output.Append("\r\n[Tunnel]\r\nIp=").Append(configuration.RelayHost).Append("\r\nPort=")
                .Append(configuration.RelayPort.Value.ToString(CultureInfo.InvariantCulture)).Append("\r\n");
        }
        return output.ToString();
    }

    /// <summary>
    /// Renders a complete multi-player spawn: host election, per-player tunnel
    /// ports, sides and colours, a shared seed, an [Other#] section per
    /// opponent, and the globally ordered starting locations.
    /// </summary>
    public static string Render(SpawnMatchPlan plan)
    {
        ArgumentNullException.ThrowIfNull(plan);
        plan.Validate();
        SpawnGameOptions options = plan.EffectiveOptions;
        foreach (SpawnParticipant participant in plan.Others.Prepend(plan.Local))
            ValidateValue(participant.Name, nameof(participant.Name));
        ValidateValue(plan.MapId, nameof(plan.MapId));
        ValidateValue(plan.GameId, nameof(plan.GameId));
        ValidateValue(plan.TunnelHost, nameof(plan.TunnelHost));

        StringBuilder output = new("; Generated by Bindery RA2/YR adapter. Do not commit.\r\n");
        output.Append("[Settings]\r\n");
        Append(output, "Name", plan.Local.Name);
        Append(output, "Port", plan.Local.TunnelPort);
        Append(output, "Side", plan.Local.Side);
        Append(output, "Color", plan.Local.Color);
        Append(output, "IsSpectator", plan.Local.IsSpectator);
        Append(output, "Host", plan.IsHost);
        Append(output, "GameID", plan.GameId);
        Append(output, "Scenario", plan.MapId);
        Append(output, "PlayerCount", plan.PlayerCount);
        Append(output, "Seed", plan.Seed);
        Append(output, "Ra2Mode", true);
        Append(output, "ForceMultiplayer", true);
        Append(output, "WriteStatistics", true);
        Append(output, "GameSpeed", options.GameSpeed);
        Append(output, "Credits", options.Credits);
        Append(output, "UnitCount", options.UnitCount);
        Append(output, "ShortGame", options.ShortGame);
        // The client spells this without the inner capital.
        Append(output, "Superweapons", options.Superweapons ? "True" : "False");
        Append(output, "Crates", options.Crates);
        Append(output, "BuildOffAlly", options.BuildOffAlly);
        Append(output, "MultiEngineer", options.MultiEngineer);
        Append(output, "Bases", options.Bases);
        Append(output, "MCVRedeploy", options.MCVRedeploy);
        Append(output, "FogOfWar", options.FogOfWar);
        Append(output, "SidebarHack", options.SidebarHack);
        Append(output, "AINamesByDifficulty", options.AINamesByDifficulty);
        Append(output, "SpecialHouseIsAlly", options.SpecialHouseIsAlly);
        Append(output, "DefeatedBecomesObserver", options.DefeatedBecomesObserver);
        // GameMode is an integer: 1 = Battle.
        Append(output, "GameMode", options.GameMode);
        Append(output, "FrameSendRate", options.FrameSendRate);
        Append(output, "Protocol", options.Protocol);
        Append(output, "ReconnectTimeout", options.ReconnectTimeout);
        // Under Protocol 0 this is the lockstep lookahead window.
        Append(output, "MaxAhead", options.MaxAhead);
        // Engine-level exit at match end, so no one has to click Continue and
        // the harness never has to kill a process to end a run.
        Append(output, "SkipScoreScreen", options.SkipScoreScreen);
        Append(output, "QuickExit", options.QuickExit);
        if (plan.AiPlayers.Count > 0) Append(output, "AIPlayers", plan.AiPlayers.Count);

        int index = 1;
        foreach (SpawnParticipant other in plan.Others)
        {
            output.Append("\r\n[Other").Append(index.ToString(CultureInfo.InvariantCulture)).Append("]\r\n");
            Append(output, "Name", other.Name);
            Append(output, "Side", other.Side);
            Append(output, "Color", other.Color);
            Append(output, "IsSpectator", other.IsSpectator);
            // In tunnel play every peer is reached through the tunnel, never by
            // its own address.
            Append(output, "Ip", plan.PeerAddress);
            Append(output, "Port", other.TunnelPort);
            index++;
        }

        // AI houses are keyed Multi{humans + n} across three sections. Only
        // AIPlayers=N, without these, produces a scenario that never loads.
        if (plan.AiPlayers.Count > 0)
        {
            AppendAiSection(output, "HouseHandicaps", plan, static ai => ai.Handicap);
            AppendAiSection(output, "HouseCountries", plan, static ai => ai.Country);
            AppendAiSection(output, "HouseColors", plan, static ai => ai.Color);
            AppendAiAlliances(output, plan);
        }

        // Written in GLOBAL player order and byte identical on every client:
        // xna-cncnet-client writes Multi{pId+1} from its global Players list,
        // and each client derives the same assignment deterministically.
        // Ordering these relative to the local player makes the two clients
        // disagree about who starts where, which desyncs the match immediately
        // -- and omitting the section entirely puts both players on one cell.
        if (plan.GlobalOrder.Any(static participant => participant.SpawnLocation >= 0))
        {
            output.Append("\r\n[SpawnLocations]\r\n");
            for (int seat = 0; seat < plan.GlobalOrder.Count; seat++)
            {
                SpawnParticipant participant = plan.GlobalOrder[seat];
                if (participant.SpawnLocation >= 0)
                    Append(output, "Multi" + (seat + 1).ToString(CultureInfo.InvariantCulture), participant.SpawnLocation);
            }
            for (int ai = 0; ai < plan.AiPlayers.Count; ai++)
            {
                if (plan.AiPlayers[ai].SpawnLocation >= 0)
                    Append(output, "Multi" + (plan.GlobalOrder.Count + ai + 1).ToString(CultureInfo.InvariantCulture), plan.AiPlayers[ai].SpawnLocation);
            }
        }

        output.Append("\r\n[Tunnel]\r\nIp=").Append(plan.TunnelHost).Append("\r\nPort=")
            .Append(plan.TunnelPort.ToString(CultureInfo.InvariantCulture)).Append("\r\n");
        return output.ToString();
    }

    private static void AppendAiSection(StringBuilder output, string section, SpawnMatchPlan plan, Func<SpawnAiParticipant, int> value)
    {
        output.Append("\r\n[").Append(section).Append("]\r\n");
        for (int ai = 0; ai < plan.AiPlayers.Count; ai++)
        {
            Append(output, "Multi" + (plan.GlobalOrder.Count + ai + 1).ToString(CultureInfo.InvariantCulture), value(plan.AiPlayers[ai]));
        }
    }

    // yrpp-spawner reads [Multi{n}_Alliances] HouseAlly{One..Eight} as
    // zero-based house indices; AI house n sits at index humans + n.
    private static void AppendAiAlliances(StringBuilder output, SpawnMatchPlan plan)
    {
        string[] allyKeys = ["HouseAllyOne", "HouseAllyTwo", "HouseAllyThree", "HouseAllyFour", "HouseAllyFive", "HouseAllySix", "HouseAllySeven"];
        for (int ai = 0; ai < plan.AiPlayers.Count; ai++)
        {
            int team = plan.AiPlayers[ai].Team;
            if (team <= 0) continue;
            int[] allies = Enumerable.Range(0, plan.AiPlayers.Count)
                .Where(other => other != ai && plan.AiPlayers[other].Team == team)
                .Select(other => plan.GlobalOrder.Count + other)
                .ToArray();
            if (allies.Length == 0) continue;
            output.Append("\r\n[Multi").Append((plan.GlobalOrder.Count + ai + 1).ToString(CultureInfo.InvariantCulture)).Append("_Alliances]\r\n");
            for (int i = 0; i < allies.Length; i++) Append(output, allyKeys[i], allies[i]);
        }
    }

    private static void Append(StringBuilder output, string key, string value) => output.Append(key).Append('=').Append(value).Append("\r\n");

    private static void Append(StringBuilder output, string key, int value) => Append(output, key, value.ToString(CultureInfo.InvariantCulture));

    private static void Append(StringBuilder output, string key, bool value) => Append(output, key, value ? "Yes" : "No");

    private static void ValidateValue(string value, string name)
    {
        if (value.Contains('\r') || value.Contains('\n') || value.Contains('\0')) throw new ArgumentException($"{name} contains a forbidden control character", name);
    }
}
